config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root "home#index"

  resource :countries, only: [:new, :create, :update]

  resources :hotel_chains do
    resources :hotels
  end

  get '/hotels', action: :index, controller: :hotels

  resources :hotels do
    get '/new_report', to: 'reports#build_report', as: 'build_new_report'
    post '/new_report', to: "reports#create_report", as: 'create_new_report'
    resources :reports, only: [:index, :new, :edit, :create, :update, :destroy]
  end

  resources :reports, only: [:show]

  resources :agencies
  resources :countries

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @balance_reports = Report.all.where(category_id: 1, user_id: current_user.id)
    @antiguity_reports = Report.all.where(category_id: 2, user_id: current_user.id)
  end

  def about

  end

  def error

  end
end

app/helpers/home_helper.rb
module HomeHelper

  def month_to_str(n)
    if n == 1
      "Enero"
    elsif n == 2
      "Febrero"
    elsif n == 3
      "Marzo"
    elsif n == 4
      "Abril"
    elsif n == 5
      "Mayo"
    elsif n == 6
      "Junio"
    elsif n == 7
      "Julio"
    elsif n == 8
      "Agosto"
    elsif n == 9
      "Septiembre"
    elsif n == 10
      "Octubre"
    elsif n == 11
      "Noviembre"
    else
      "Diciembre"
    end
  end
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/error.html.erb
<h1>Home#error</h1>
<p>Find me in app/views/home/error.html.erb</p>

app/views/home/index.html.erb
<style>
  body {
    font-size: .875rem;
  }

  .feather {
    width: 16px;
    height: 16px;
    vertical-align: text-bottom;
  }

  /*
   * Sidebar
   */

  .sidebar {
    top: 0;
    bottom: 0;
    left: 0;
    z-index: 100; /* Behind the navbar */
    padding: 48px 0 0; /* Height of navbar */
    box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
  }

  .sidebar-sticky {
    position: relative;
    top: 0;
    height: calc(100vh - 48px);
    padding-top: .5rem;
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
  }

  @supports ((position: -webkit-sticky) or (position: sticky)) {
    .sidebar-sticky {
      position: -webkit-sticky;
      position: sticky;
    }
  }

  .sidebar .nav-link {
    font-weight: 500;
    color: #333;
  }

  .sidebar .nav-link .feather {
    margin-right: 4px;
    color: #999;
  }

  .sidebar .nav-link.active {
    color: #007bff;
  }

  .sidebar .nav-link:hover .feather,
  .sidebar .nav-link.active .feather {
    color: inherit;
  }

  .sidebar-heading {
    font-size: .75rem;
    text-transform: uppercase;
  }

  /*
   * Content
   */

  [role="main"] {
    padding-top: 133px; /* Space for fixed navbar */
  }

  @media (min-width: 768px) {
    [role="main"] {
      padding-top: 48px; /* Space for fixed navbar */
    }
  }

  /*
   * Navbar
   */

  .navbar .form-control {
    padding: .75rem 1rem;
    border-width: 0;
    border-radius: 0;
  }

  .form-control-dark {
    color: #fff;
    background-color: rgba(255, 255, 255, .1);
    border-color: rgba(255, 255, 255, .1);
  }

  .form-control-dark:focus {
    border-color: transparent;
    box-shadow: 0 0 0 3px rgba(255, 255, 255, .25);
  }
</style>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>">
              Inicio <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= hotels_path %>">
              Hoteles
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= agencies_path %>">
              Agencias
            </a>
          </li>
        </ul>

<!--                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">-->
<!--                  <span>Saved reports</span>-->
<!--                  <a class="d-flex align-items-center text-muted" href="#">-->
<!--                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>-->
<!--                  </a>-->
<!--                </h6>-->
<!--                <ul class="nav flex-column mb-2">-->
<!--                  <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">-->
<!--                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>-->
<!--                      Current month-->
<!--                    </a>-->
<!--                  </li>-->
<!--                  <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">-->
<!--                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>-->
<!--                      Last quarter-->
<!--                    </a>-->
<!--                  </li>-->
<!--                  <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">-->
<!--                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>-->
<!--                      Social engagement-->
<!--                    </a>-->
<!--                  </li>-->
<!--                  <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">-->
<!--                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>-->
<!--                      Year-end sale-->
<!--                    </a>-->
<!--                  </li>-->
<!--                </ul>-->
      </div>
    </nav>
    <main role="main" class="container col-md-9 ml-sm-auto col-lg-10 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
      <h2>Balance de comprobacion</h2>
      <div class="table-responsive center">
        <table class="table table-bordered table-hover table-sm">
          <thead>
          <tr>
            <th>Fecha</th>
            <th>Hotel</th>
            <th>Trabajador</th>
          </tr>
          </thead>
          <tbody>
          <% @balance_reports.each do |report| %>
            <tr>
              <td><%= report.date.day  %> de <%= month_to_str(report.date.month) %> del <%= report.date.year %></td>
              <td><%= link_to "Hotel Asociado", hotel_path(report.hotel_id)%></td>
              <td><%= report.uploaded_by %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <h2>Antiguedad de partidas</h2>
      <div class="table-responsive">
        <table class="table table-bordered table-hover table-sm">
          <thead>
          <tr>
            <th>Fecha</th>
            <th>Hotel</th>
            <th>Trabajador</th>
          </tr>
          </thead>
          <tbody>
          <% @antiguity_reports.each do |report| %>
            <tr>
              <td><%= report.date.day  %> de <%= month_to_str(report.date.month) %> del <%= report.date.year %></td>
              <td><%= link_to "Hotel Asociado", hotel_path(report.hotel_id)%></td>
              <td><%= report.uploaded_by %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>