config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root "home#index"

  resource :countries, only: [:new, :create, :update]

  resources :hotel_chains do
    resources :hotels
  end

  get '/hotels', action: :index, controller: :hotels

  resources :hotels do
    get '/new_report', to: 'reports#build_report', as: 'build_new_report'
    post '/new_report', to: "reports#create_report", as: 'create_new_report'
    resources :reports, only: [:index, :new, :edit, :create, :update, :destroy]
  end

  resources :reports, only: [:show]

  resources :agencies
  resources :countries

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  # after_create :set_filename

  belongs_to :category
  belongs_to :hotel
  belongs_to :user

  mount_uploader :excel, ExcelUploader

  # def report_path
  #   ActiveStorage::Blob.service.send(:path_for, spreadsheet.key)
  # end

  # def set_filename
  #   if self.spreadsheet.attached?
  #     if self.category_id == 1
  #       self.spreadsheet.blob.update(filename: "Balance_de_#{self.date.day}_#{self.date.month}_hasta_#{self.end_date.day}_#{self.end_date.month}.#{self.spreadsheet.filename.extension}")
  #     else
  #       puts self.spreadsheet.filename.to_s
  #       self.spreadsheet.blob.update(filename: "Antiguedad_de_#{self.date.day}_#{self.date.month}_hasta_#{self.end_date.day}_#{self.end_date.month}.#{self.spreadsheet.filename.extension}")
  #       debugger
  #     end
  #   end
  # end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  require 'roo-xls'
  require 'axlsx'

  #Creating constant...
  C = 3 #Agencies
  E = 5
  F = 6
  G = 7
  H = 8
  I = 9
  J = 10
  K = 11
  L = 12
  M = 13
  N = 14
  O = 15
  P = 16
  Q = 17
  R = 18

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  def build_report
    @hotel = Hotel.find_by(params[:hotel_id])
    @report = @hotel.reports.new
  end


  #Auxiliar function
  def add_column(sheet, from, to, from_doc)
    from_doc.column(from).each_with_index do |member, index|
      sheet[index,to-1] = member #Name of Agency
    end
  end
  
  def create_report(doc_balance_path, doc_antiquity_path)
    # Reading documents...
    doc_antiquity = Roo::Spreadsheet.open(doc_antiquity_path, extension: :xlsx)
    doc_balance = Roo::Spreadsheet.open(doc_balance_path, extension: :xlsx)

    # Creating report...
    doc_report = Spreadsheet::Workbook.new
    sheet1_doc_report = doc_report.create_worksheet

    #Building report...
    add_column(sheet1_doc_report,C, 1, doc_balance)
    add_column(sheet1_doc_report,H, E, doc_balance)
    add_column(sheet1_doc_report,G, F, doc_balance)
    add_column(sheet1_doc_report,G, M, doc_antiquity)
    add_column(sheet1_doc_report,I, O, doc_antiquity)
    add_column(sheet1_doc_report,J, P, doc_antiquity)
    add_column(sheet1_doc_report,Q, K, doc_antiquity)

    ### From doc_atiquity doing (column E) + (column F)
    col_E = doc_antiquity.column(E)
    col_F = doc_antiquity.column(F)
    col_sum = []
    len = col_E.length
    0.upto(len-1) do |i| 
        begin
            a = col_E[i].to_f
            b = col_F[i].to_f
            col_sum << (a + b).to_s
        rescue => exception
            col_sum << "".to_s   
        end
    end

    col_sum.each_with_index do |member, index|
        sheet1_doc_report[index,L-1] = member
    end
    #TODO: Make zero to R column

    # #Saving report...
    doc_report.write './docs/report.xls'
  end

  # GET /reports/new
  def new
    @hotel = Hotel.find_by(params[:hotel_id])
    @report = @hotel.reports.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @hotel = Hotel.find_by(params[:hotel_id])
    @report = @hotel.reports.new(report_params)

    respond_to do |format|
      if @report.save
        flash[:success] = "Report created successfuly."
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        flash[:alert] = "Errors where found."
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to report_path(@report.id), notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: report_path(@report.id) }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:date, :end_date, :category_id, :user_id, :excel, :uploaded_by)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<style>
  body{
    text-align: center!important;
  }
  .form-signin{
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
</style>

<%= form_with(model: [ @hotel, report ], local: true, html: {class: "form-signin"}) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.datetime_select :date, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :excel %>
    <%= form.file_field :excel, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label 'category' %>
    <%= form.select(:category_id) do %>
      <% [['Balance de comprobacion', 1], ['Antiguedad de partidas', 2]].each do |item| %>
        <%= content_tag(:option, item.first, value: item.last) %>
      <% end %>
    <% end %>
  </div>

  <div class="form-group" hidden>
    <%= form.label :user_id %>
    <%= form.number_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group" hidden>
    <%= form.label :uploaded_by %>
    <%= form.text_field :uploaded_by, value: current_user.name %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary"%>
  </div>

<% end %>

app/views/reports/build_report.html.erb
<style>
  body{
    text-align: center!important;
  }
  .form{
    width: 100%;
    max-width: 400px;
    padding: 15px;
    margin: auto;
  }
</style>

<%= form_with(model: [ @hotel, @report ], local: true, url: hotel_create_new_report_path, html: {class: "form", :method => :post}) do |form| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>
      <ul>
        <% @report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" hidden>
    <%= form.label :category %>
    <%= form.number_field :category_id, value: 3%>
  </div>

  <label>Seleccione la fecha de inicio del informe a crear</label>
  <div class="form-group">
    <%= form.datetime_select :date, class: "form-control"  %>
  </div>

  <label>Seleccione la fecha final del informe a crear</label>
  <div class="form-group">
    <%= form.datetime_select :end_date, class: "form-control"  %>
  </div>

  <div class="form-group">
    <label>Seleccione el informe de Balance</label>
    <%= form.collection_select(:balance_id, Report.all.where(category_id: 1), :id, :date)%>
  </div>

  <div class="form-group">
    <label>Seleccione el informe de Antiguedad</label>
    <%= form.collection_select(:antiguedad_id, Report.all.where(category_id: 2), :id, :date)%>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary"%>
  </div>

<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.date %></td>
        <td><%= report.end_date %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_hotel_report_path(report.hotel_id, report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_hotel_report_path %>

app/views/reports/new.html.erb
<h1>Nuevo Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', hotel_reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @report.date %>
</p>

<%= link_to 'Edit', edit_hotel_report_path(@report) %> |
<%= link_to 'Back', hotel_reports_path(@report.hotel_id) %>